---

is_debug: true
listen:
  type: port
  bind_ip: 0.0.0.0
  port: 10002
mongodb:
  host: localhost
  port: 27017
  username:
  password:
  auth_db: notes_system
  database: notes_system
  collection: notes